# Fetch  the gile 
# file
# inlinefile
---
- name: Preparing servers
  hosts: web,localhost
  become: yes
  tasks:
  - name: Fetch the /var/log/secure log file from managed hosts
    ansible.builtin.fetch:
      src: /var/log/secure
      dest: secure-backups

  - name: Ensure the /home/devops/files directory exists
    ansible.builtin.file:
      path: /home/ansible/files
      state: directory
      owner: ansible
      group: ansible
      mode: 0775
      setype: samba_share_t

  - name: Add a single line of text to a file
    ansible.builtin.lineinfile:
      path: /home/ansible/files/users.txt
      line: This line was added by the lineinfile module
      state: present
      create: true
      owner: ansible
      group: ansible
      mode: 0664
